### ISSUE TITLE
Only Column Headers

### ISSUE THREAD

**Issue by mueth5525** [koxm/MMM-SpaceX#1]
The module has worked fine for the past few months but the other day it stopped appearing. The only thing I see is the column headers, no information (launches, orbit, dates, etc.). Any ideas?

**Comment by koxm** [comment]
It seems that the SpaceX api has stopped working or is temporarily down. My recommendation is to use my other module: MMM-SpaceLaunchNow.
This works on the basis of a different API and also shows launches from other agencies. All in all, a better module. Have fun with it.

**Comment by mueth5525** [comment]
I will check it out. Where can I find it at? (Sorry, new to this stuff)

**Comment by koxm** [comment]
It's over here: https://github.com/koxm/MMM-SpaceLaunchNow
